server {
    listen 80;
    server_name resultado.algorah.bond;

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/Elecciones/elecciones.sock;
    }

    # Configuración opcional para mejorar el rendimiento de archivos estáticos
    location /static {
        alias /home/ubuntu/Elecciones/static;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
